// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIXFpsQaXRHnxsUE2Kr7vDMyB7B_yvsBQ',
    appId: '1:22088865381:web:975172e5b895a776f7588c',
    messagingSenderId: '22088865381',
    projectId: 'alpinestars-fa28a',
    authDomain: 'alpinestars-fa28a.firebaseapp.com',
    storageBucket: 'alpinestars-fa28a.firebasestorage.app',
    measurementId: 'G-JQKWTND6YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Cl2mBjofz8I_Kc5VNmpeztVh-Uqlezk',
    appId: '1:22088865381:android:55be318c2d2a5f1df7588c',
    messagingSenderId: '22088865381',
    projectId: 'alpinestars-fa28a',
    storageBucket: 'alpinestars-fa28a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHQAYJwaA0m5FJVof6arB4aRToFlktV-E',
    appId: '1:22088865381:ios:4b272b6874977feaf7588c',
    messagingSenderId: '22088865381',
    projectId: 'alpinestars-fa28a',
    storageBucket: 'alpinestars-fa28a.firebasestorage.app',
    iosBundleId: 'com.example.motogear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHQAYJwaA0m5FJVof6arB4aRToFlktV-E',
    appId: '1:22088865381:ios:4b272b6874977feaf7588c',
    messagingSenderId: '22088865381',
    projectId: 'alpinestars-fa28a',
    storageBucket: 'alpinestars-fa28a.firebasestorage.app',
    iosBundleId: 'com.example.motogear',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIXFpsQaXRHnxsUE2Kr7vDMyB7B_yvsBQ',
    appId: '1:22088865381:web:320ca29aaea238e8f7588c',
    messagingSenderId: '22088865381',
    projectId: 'alpinestars-fa28a',
    authDomain: 'alpinestars-fa28a.firebaseapp.com',
    storageBucket: 'alpinestars-fa28a.firebasestorage.app',
    measurementId: 'G-Z7LMG6KYPN',
  );
}
