final seedProducts = <Map<String, dynamic>>[
  {
    "id": "gp_force_v2_air_leather_jacket",
    "category": "Jackets",
    "title": "GP Force V2 Air Leather Jacket",
    "subtitle": "Motorcycling • Apparel • Jackets",
    "priceLabel": "€469.95",
    "priceValue": 469.95,
    "coverImage": "assets/images/gpforce_v2_air_leather_jacket.png",
    "images": [
      "assets/images/gpforce_v2_air_leather_jacket.png",
      "assets/images/gpforce_v2_air_leather_jacket_back.png",
    ],
    "techAirReady": true,
    "waterproof": false,
    "bullets": [
      "Tech-Air® Ready",
      "CE-certified garment (AA Class)",
      "Airflow construction",
      "Perforated leather for ventilation and breathability",
      "Sport fit for active riding comfort and protection",
      "High-stretch panels for freedom of movement",
      "Comfort-driven ergonomic cuffs",
      "Pre-curved elbows reduce rider fatigue",
    ],
    "sizes": ["46", "48", "50", "52", "54", "56", "58"],
  },
  {
    "id": "supertech_r10_solid_helmet",
    "category": "Helmets",
    "title": "Supertech R10 Solid Helmet",
    "subtitle": "Motorcycling • Helmets",
    "priceLabel": "€989.95",
    "priceValue": 989.95,
    "coverImage": "assets/images/supertech_r10_solid_helmet.png",
    "images": [
      "assets/images/supertech_r10_solid_helmet.png",
      "assets/images/supertech_r10_solid_helmet_front.png",
    ],
    "techAirReady": false,
    "waterproof": false,
    "bullets": [
      "Premium performance helmet developed through extensive testing",
      "Carbon shell construction (multi-layer composite)",
      "Designed for excellent ventilation and comfort",
      "Lightweight performance-focused build",
    ],
    "sizes": ["S", "M", "L", "XL", "2XL"],
  },
  {
    "id": "wt8_goretex_insulated_gloves",
    "category": "Gloves",
    "title": "WT-8 GORE-TEX Insulated Gloves",
    "subtitle": "Motorcycling • Apparel • Gloves",
    "priceLabel": "€189.95",
    "priceValue": 189.95,
    "coverImage": "assets/images/wt-8_gore-tex_insulated_gloves.png",
    "images": [
      "assets/images/wt-8_gore-tex_insulated_gloves.png",
      "assets/images/wt-8_gore-tex_insulated_gloves_back.png",
    ],
    "techAirReady": false,
    "waterproof": true,
    "bullets": [
      "GORE-TEX construction for wet-weather performance",
      "Gore-grip bonded construction for better feel and control",
      "Leather palm reinforcements & padding for abrasion resistance",
      "PrimaLoft® GOLD Insulation Eco for warmth",
      "Long-cuff protection with secure closure",
      "Touchscreen compatible conductive fingertips",
    ],
    "sizes": ["L", "XL", "XXL", "3XL", "4XL"],
  },
  {
    "id": "stella_missile_v3_leather_pants",
    "category": "Pants",
    "title": "Stella Missile V3 Leather Pants",
    "subtitle": "Motorcycling • Apparel • Pants",
    "priceLabel": "€469.95",
    "priceValue": 469.95,
    "coverImage": "assets/images/stella_missle_v3_leather_pants.png",
    "images": [
      "assets/images/stella_missle_v3_leather_pants.png",
      "assets/images/stella_missle_v3_leather_pants_back.png",
    ],
    "techAirReady": true,
    "waterproof": false,
    "bullets": [
      "Ventilation panel on knee delivers maximum airflow",
      "Comfort fit follows the contours of the knee",
      "High Flex design for optimized fit and freedom of movement",
      "Dual layers in exposed areas for abrasion resistance",
      "Pre-curved leg construction helps reduce fatigue",
      "Strategically positioned thigh ventilation for cooling",
      "Waist connection zipper attaches to Alpinestars jackets",
      "Hook and loop waist adjuster for secure fit",
      "Internal mesh lining with stretch panels for comfort",
      "GP-R Lite internal protection on knee",
      "Replaceable sport knee sliders for impact & abrasion",
    ],
    "sizes": ["46", "48", "50", "52", "54", "56", "58"],
  },
  {
    "id": "faster4_drystar_shoes",
    "category": "Footwear",
    "title": "Faster-4 Drystar® Shoes",
    "subtitle": "Motorcycling • Footwear",
    "priceLabel": "€179.95",
    "priceValue": 179.95,
    "coverImage": "assets/images/drystar_shoes.png",
    "images": [
      "assets/images/drystar_shoes.png",
      "assets/images/drystar_shoes_pair.png",
    ],
    "techAirReady": false,
    "waterproof": true,
    "bullets": [
      "Drystar® membrane for moisture management",
      "Seamless microfiber construction for durability",
      "Advanced rubber compound sole for grip and stability",
      "Heel dampening in the midsole for comfort",
      "Tongue and collar padding for ankle and foot support",
    ],
    "sizes": [
      "EU 40",
      "EU 41",
      "EU 42",
      "EU 43",
      "EU 44",
      "EU 45",
    ],
  },
];
